/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AboutPage: typeof import('./src/pages/AboutPage')['default']
  const App: typeof import('./src/App')['default']
  const BrowserRouter: typeof import('react-router')['BrowserRouter']
  const Button: typeof import('antd')['Button']
  const ConfigProvider: typeof import('antd')['ConfigProvider']
  const DATA_ABOUT: typeof import('./src/constans/constant')['DATA_ABOUT']
  const Link: typeof import('react-router')['Link']
  const MainPage: typeof import('./src/pages/MainPage')['default']
  const NAV_ITEMS: typeof import('./src/constans/constant')['NAV_ITEMS']
  const NavLink: typeof import('react-router-dom')['NavLink']
  const Navigate: typeof import('react-router')['Navigate']
  const Outlet: typeof import('react-router')['Outlet']
  const PROJECTS_DATA: typeof import('./src/constans/constant')['PROJECTS_DATA']
  const ProjectsPage: typeof import('./src/pages/ProjectsPage')['default']
  const Route: typeof import('react-router')['Route']
  const RouterProvider: typeof import('react-router')['RouterProvider']
  const Routes: typeof import('react-router')['Routes']
  const TECHNOLOGIES_ITEMS: typeof import('./src/constans/constant')['TECHNOLOGIES_ITEMS']
  const createBrowserRouter: typeof import('react-router')['createBrowserRouter']
  const createRef: typeof import('react')['createRef']
  const eslintConfig: typeof import('./eslint.config.js')['default']
  const forwardRef: typeof import('react')['forwardRef']
  const helloworld: typeof import('./src/components/helloworld')['default']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const motion: typeof import('framer-motion')['motion']
  const postcssConfig: typeof import('./postcss.config.js')['default']
  const projectCard: typeof import('./src/components/projectCard')['default']
  const projectsCarousel: typeof import('./src/constans/constant')['projectsCarousel']
  const router: typeof import('./src/routes/router')['default']
  const startTransition: typeof import('react')['startTransition']
  const tailwindConfig: typeof import('./tailwind.config.js')['default']
  const techCarousel: typeof import('./src/constans/constant')['techCarousel']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useHref: typeof import('react-router-dom')['useHref']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInRouterContext: typeof import('react-router-dom')['useInRouterContext']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useLinkClickHandler: typeof import('react-router-dom')['useLinkClickHandler']
  const useLocation: typeof import('react-router')['useLocation']
  const useMatch: typeof import('react-router')['useMatch']
  const useMemo: typeof import('react')['useMemo']
  const useNavigate: typeof import('react-router')['useNavigate']
  const useNavigationType: typeof import('react-router-dom')['useNavigationType']
  const useOutlet: typeof import('react-router-dom')['useOutlet']
  const useOutletContext: typeof import('react-router-dom')['useOutletContext']
  const useParams: typeof import('react-router')['useParams']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useResolvedPath: typeof import('react-router-dom')['useResolvedPath']
  const useRoutes: typeof import('react-router-dom')['useRoutes']
  const useSearchParams: typeof import('react-router-dom')['useSearchParams']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
  const viteConfig: typeof import('./vite.config')['default']
  const viteConfigD: typeof import('../ice-cream/vite.config.d')['default']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { DataAboutType, dataProjectsType } from './src/constans/types'
  import('./src/constans/types')
}
