/* generated by unplugin-react-components */
export {}
declare global{
	const App: typeof import('./src/App')['default']
	const ProjectCard: typeof import('./src/components/projectCard')['default']
	const AboutPage: typeof import('./src/pages/AboutPage')['default']
	const MainPage: typeof import('./src/pages/MainPage')['default']
	const ProjectsPage: typeof import('./src/pages/ProjectsPage')['default']
	const AppRouter: typeof import('./src/routes/router')['default']
}